[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3') && has('nvim')"
on_event = 'VimEnter'
hook_add="""
    let g:python3_host_prog = expand('~/.pyenv/versions/neovim3/bin/python')
"""

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
hook_add="""
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft='python'
if = "has('python3') && has('nvim')"
hook_post_update = """
    call system("git submodule update --init")
"""
