[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends='unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kana/vim-smartinput'
