[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3') && has('nvim')"
on_event = 'VimEnter'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
on_event = 'InsertEnter'
hook_add="""
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
"""

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
if = "has('python3') && has('nvim')"
hook_post_update = """
    call system("git submodule update --init")
"""

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
on_event = 'InsertEnter'
rev = 'next'
hook_post_update = """
    call system("sh install.sh")
"""
hook_add = """
    let g:LanguageClient_serverCommands = {
    \ 'javascript': ['javascript-typescript-langserver'],
    \ }
    nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
    nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
    nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
"""

