[[plugins]]
repo = 'Shougo/denite.nvim'
if = "has('python3')"
on_cmd = 'Denite'
hook_add="""
"""

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('python3')"
hook_add="""
    let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft='python'
if = "has('python3') && has('nvim')"
hook_post_update = """
    call system("git submodule update --init")
"""
